version: '3.4'

services:
  eventstore:
    image: eventstore/eventstore:release-4.0.2
    ports:
      - "2113:2113"
      - "1113:1113"
    environment:
      - RUN_PROJECTIONS = All
    networks:
      - leanda-net

  redis:
    image: redis:4-alpine
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    networks:
      - leanda-net

  rabbitmq:
    image: leanda/rabbitmq
    hostname: "leanda"
    environment:
      - RABBITMQ_DEFAULT_VHOST=leanda
    ports:
      - "8282:15672"
      - "5672:5672"
    networks:
      - leanda-net

  mongo:
    image: mongo:3.6
    ports:
      - "27017:27017"
    networks:
      - leanda-net

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_DATABASE: keycloak
      POSTGRES_ROOT_PASSWORD: keycloak
      pgdata: data-pstgresql
    networks:
      - leanda-net

  keycloak:
    build: KeyCloak
    environment:
      DB_VENDOR: POSTGRES
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_PORT_5432_TCP_ADDR: postgres
      POSTGRES_DATABASE: keycloak
      JDBC_PARAMS: 'connectTimeout=30'
    ports:
      - '8080:8080'
    networks:
      - leanda-net
    depends_on:
      - postgres

  core-backend:
    container_name: leanda-backend
    image: leanda/core-backend:${TAG_VERSION-latest}
    entrypoint: /bin/bash
    environment:
      - OSDR_LOG_FOLDER=/logs
      - OSDR_MONGO_DB=mongodb://mongo:27017/osdr
      - OSDR_RABBIT_MQ=rabbitmq://guest:guest@rabbitmq:5672/leanda
      - OSDR_EVENT_STORE=ConnectTo=tcp://admin:changeit@eventstore:1113
      - OSDR_REDIS=redis
      - OSDR_LOG_LEVEL=${OSDR_LOG_LEVEL}
    command: ./wait-for-it.sh rabbitmq:15672 -t 30 -- ./Sds.Osdr.Domain.BackEnd
    volumes:
      - ${OSDR_LOG_FOLDER}:/logs
    networks:
      - leanda-net
    depends_on:
      - rabbitmq
      - eventstore
      - redis
      - mongo

  core-frontend:
    container_name: leanda-frontend
    image: leanda/core-frontend:${TAG_VERSION-latest}
    entrypoint: /bin/bash
    environment:
      - OSDR_LOG_FOLDER=/logs
      - OSDR_MONGO_DB=mongodb://mongo:27017/osdr
      - OSDR_RABBIT_MQ=rabbitmq://guest:guest@rabbitmq:5672/leanda
      - OSDR_EVENT_STORE=ConnectTo=tcp://admin:changeit@eventstore:1113
      - OSDR_REDIS=redis
      - OSDR_LOG_LEVEL=${OSDR_LOG_LEVEL}
    command: ./wait-for-it.sh rabbitmq:15672 -t 30 -- ./Sds.Osdr.Domain.FrontEnd
    volumes:
      - ${OSDR_LOG_FOLDER}:/logs
    networks:
      - leanda-net
    depends_on:
      - rabbitmq
      - eventstore
      - redis
      - mongo

  core-sagahost:
    container_name: leanda-sagahost
    image: leanda/core-sagahost:${TAG_VERSION-latest}
    entrypoint: /bin/bash
    environment:
      - OSDR_LOG_FOLDER=/logs
      - OSDR_MONGO_DB=mongodb://mongo:27017/osdr
      - OSDR_RABBIT_MQ=rabbitmq://guest:guest@rabbitmq:5672/leanda
      - OSDR_LOG_LEVEL=${OSDR_LOG_LEVEL}
    command: ./wait-for-it.sh rabbitmq:15672 -t 30 -- ./Sds.Osdr.Domain.SagaHost
    volumes:
      - ${OSDR_LOG_FOLDER}:/logs
    networks:
      - leanda-net
    depends_on:
      - rabbitmq
      - mongo

  core-persistence:
    container_name: leanda-persistence
    image: leanda/core-persistence:${TAG_VERSION-latest}
    entrypoint: /bin/bash
    environment:
      - OSDR_LOG_FOLDER=/logs
      - OSDR_MONGO_DB=mongodb://mongo:27017/osdr
      - OSDR_RABBIT_MQ=rabbitmq://guest:guest@rabbitmq:5672/leanda
      - OSDR_LOG_LEVEL=${OSDR_LOG_LEVEL}
    command: ./wait-for-it.sh rabbitmq:15672 -t 30 -- ./Sds.Osdr.Persistence
    volumes:
      - ${OSDR_LOG_FOLDER}:/logs
    networks:
      - leanda-net
    depends_on:
      - rabbitmq
      - mongo

  blob-storage-api:
    container_name: blob-storage-api
    image: leanda/blob-storage-webapi
    entrypoint: /bin/bash
    environment:
      - IDENTITY_SERVER_URL=http://keycloak:8080/auth/realms/OSDR
      - OSDR_LOG_FOLDER=/logs
      - OSDR_MONGO_DB=mongodb://mongo:27017/osdr
      - OSDR_RABBIT_MQ=rabbitmq://guest:guest@rabbitmq:5672/leanda
      - SWAGGER_BASEPATH=/blob/v1
    command: ./wait-for-it.sh rabbitmq:15672 -t 30 -- ./wait-for-it.sh keycloak:8080 -t 30 -- ./Sds.Storage.Blob.WebApi
    volumes:
      - ${OSDR_LOG_FOLDER}:/logs
    networks:
      - leanda-net
    ports:
      - "18006:18006"
    depends_on:
      - keycloak

  integration:
    container_name: leandas-integration-tests
    image: leanda/integration:${TAG_VERSION-latest}
    entrypoint: /bin/bash
    environment:
      - IDENTITY_SERVER_URL=http://keycloak:8080/auth/realms/OSDR
    #  - OSDR_REDIS=redis
      - OSDR_LOG_FOLDER=/logs
      - OSDR_MONGO_DB=mongodb://mongo:27017/osdr_dev
      - OSDR_GRID_FS=mongodb://mongo:27017/osdr_dev
      - OSDR_RABBIT_MQ=rabbitmq://guest:guest@rabbitmq:5672/leanda
      - OSDR_EVENT_STORE=ConnectTo=tcp://admin:changeit@eventstore:1113
    #command: ./wait-for-it.sh rabbitmq:15672 -t 30 -- ./wait-for-it.sh http://blob-storage-api:18006 -t 30 -- dotnet vstest ./Sds.Osdr.IntegrationTests.dll /logger:console;verbosity="normal"
    command: ./wait-for-it.sh rabbitmq:15672 -t 30 -- ./wait-for-it.sh http://blob-storage-api:18006 -t 30 -- dotnet vstest ./Sds.Osdr.IntegrationTests.dll /logger:"trx;LogFileName=integrationtests-results-${BUILD_NUMBER}.xml" /ResultsDirectory:/results
    volumes:
      - ${OSDR_LOG_FOLDER}:/logs
      - ${OSDR_LOG_FOLDER}:/results
    networks:
      - leanda-net
    depends_on:
      - blob-storage-api
      - core-backend
      - core-frontend
      - core-sagahost
      - core-persistence
 
networks:
    leanda-net:
